---
- name: Remove Domain Mapping from Master Relay
  hosts: all
  become: true
  vars:
    # Ensure these are passed from NestJS
    mail_domain: "{{ target_domain }}"

  tasks:
    - name: "CRITICAL SAFETY: Abort if mail_domain is empty"
      ansible.builtin.fail:
        msg: "The variable 'mail_domain' is empty. Task aborted to prevent accidental file corruption!"
      when: mail_domain is not defined or mail_domain | length == 0

    - name: Escape domain for sed
      ansible.builtin.set_fact:
        escaped_domain: "{{ mail_domain | replace('.', '\\.') }}"

    - name: Remove relay mapping from relay_by_sender file
      ansible.builtin.shell: |
        sed -i '/^@{{ escaped_domain }}\s/d' /etc/postfix/relay_by_sender
      notify:
      - Run postmap
      - Restart postfix


    - name: Debug mail_domain value
      ansible.builtin.debug:
        msg: "mail_domain is: '{{ mail_domain }}'"

  handlers:
    - name: Run postmap
      ansible.builtin.command: postmap /etc/postfix/relay_by_sender

    - name: Restart postfix
      ansible.builtin.systemd:
        name: postfix
        state: restarted
